vich_uploader:
    db_driver: orm

    mappings:
        service_photo:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'

        projet_image:
            uri_prefix: /images/projets
            upload_destination: '%kernel.project_dir%/public/images/projets'


